version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m pip install -U pip
      - run: pip install -r GitHubApi567-hw3a/requirements.txt
      - run: python -m unittest discover -s GitHubApi567-hw3a -p "test_*.py" -v
workflows:
  build_and_test:
    jobs:
      - test
